version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: certpilot-backend-dev
    restart: always
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - cert-data:/etc/certpilot/certificates
      - acme-challenge:/app/.well-known
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/certpilot
      - JWT_SECRET=dev_jwt_secret_here
      - DEBUG=express:*
      - CERT_DIR=/etc/certpilot/certificates
    command: npm run dev
    depends_on:
      - mongo
    networks:
      - certpilot-network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: certpilot-frontend-dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
      - acme-challenge:/app/.well-known
    environment:
      - NODE_ENV=development
      - VITE_API_URL=/api
    depends_on:
      - backend
    networks:
      - certpilot-network

  mongo:
    image: mongo:latest
    container_name: certpilot-mongo-dev
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - certpilot-network

networks:
  certpilot-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  cert-data:
    driver: local
  acme-challenge:
    driver: local
  frontend-node-modules:
    driver: local 