version: '3.8'

services:
  backend:
    build: ./backend
    container_name: certpilot-backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - cert-data:/etc/certpilot/certificates
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/certpilot
      - JWT_SECRET=your_jwt_secret_here
      - CERT_DIR=/etc/certpilot/certificates
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: certpilot-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    container_name: certpilot-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
  cert-data:
    driver: local 